import { createInterface } from 'readline';
import { randomBytes } from 'crypto';
import { existsSync, readFileSync, writeFileSync, mkdirSync, cpSync, readdirSync } from 'fs';
import { homedir, platform, release, type as osType } from 'os';
import { join, resolve } from 'path';
import { fileURLToPath } from 'url';
import { execFileSync } from 'child_process';
import { registerAgents } from './mcp-register.js';
import { installClaudeHooks } from './setup-hooks.js';
import { installJobs } from './setup-jobs.js';

const HOME = homedir();
// fileURLToPath handles Windows drive letters correctly (avoids C:\C:\ duplication)
const PROJECT_ROOT = resolve(fileURLToPath(new URL('.', import.meta.url)), '..', '..');

// ---------------------------------------------------------------------------
// Utility helpers
// ---------------------------------------------------------------------------

function out(text) { process.stdout.write(text); }
function outln(text = '') { process.stdout.write(text + '\n'); }

function genHex(bytes = 32) { return randomBytes(bytes).toString('hex'); }
function genBase64(bytes = 32) { return randomBytes(bytes).toString('base64'); }

function which(cmd) {
  try {
    execFileSync('which', [cmd], { stdio: 'ignore' });
    return true;
  } catch { return false; }
}

function detectVaultPath() {
  const candidates = [
    join(HOME, 'obsidian-vault'),
    join(HOME, 'Documents', 'Obsidian'),
    join(HOME, 'Obsidian'),
  ];
  for (const p of candidates) {
    if (existsSync(p)) return p;
  }
  return null;
}

// Parse KEY=value lines from a .env file; ignores comments and blanks.
export function parseEnvFile(content) {
  const out = {};
  for (const line of content.split('\n')) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

// Read the existing .env so re-running setup preserves secrets instead of rotating them.
function loadExistingEnv() {
  const envPath = join(PROJECT_ROOT, '.env');
  if (!existsSync(envPath)) return {};
  return parseEnvFile(readFileSync(envPath, 'utf8'));
}

// ---------------------------------------------------------------------------
// Readline prompt helpers
// ---------------------------------------------------------------------------

function createRl() {
  return createInterface({ input: process.stdin, output: process.stdout });
}

function ask(rl, question, defaultVal = '') {
  const suffix = defaultVal ? ` [${defaultVal}]` : '';
  return new Promise(resolve => {
    rl.question(`  ${question}${suffix}: `, answer => {
      resolve(answer.trim() || defaultVal);
    });
  });
}

async function askChoice(rl, question, choices, defaultIdx = 0) {
  outln();
  choices.forEach((c, i) => {
    const marker = i === defaultIdx ? '>' : ' ';
    outln(`  ${marker} ${i + 1}) ${c}`);
  });
  const answer = await ask(rl, question, String(defaultIdx + 1));
  const idx = parseInt(answer, 10) - 1;
  if (idx >= 0 && idx < choices.length) return idx;
  return defaultIdx;
}

async function askMulti(rl, question, choices) {
  outln();
  choices.forEach((c, i) => {
    outln(`    ${i + 1}) ${c}`);
  });
  outln(`    A) All`);
  const answer = await ask(rl, question, 'A');
  if (answer.toUpperCase() === 'A') return choices.map((_, i) => i);
  return answer.split(/[,\s]+/).map(s => parseInt(s, 10) - 1).filter(i => i >= 0 && i < choices.length);
}

// ---------------------------------------------------------------------------
// Environment detection
// ---------------------------------------------------------------------------

function detectEnvironment() {
  const env = {
    os: `${osType()} ${platform()} ${release()}`,
    nodeVersion: process.version,
    tools: {},
  };

  const toolMap = {
    claude: 'Claude Code',
    codex: 'OpenAI Codex CLI',
    gemini: 'Google Gemini CLI',
    ollama: 'Ollama',
  };

  for (const [cmd, label] of Object.entries(toolMap)) {
    env.tools[cmd] = { label, available: which(cmd) };
  }

  return env;
}

// ---------------------------------------------------------------------------
// Config generation
// ---------------------------------------------------------------------------

function buildEnvContent(cfg) {
  const lines = [
    '# Knowledge Base Server Configuration',
    `# Generated by setup wizard on ${new Date().toISOString()}`,
    '',
    '# Server port for the dashboard',
    `KB_PORT=${cfg.port}`,
    '',
    '# Dashboard login password',
    `KB_PASSWORD=${cfg.password}`,
    '',
    '# Obsidian vault path (leave empty if not using Obsidian)',
    `OBSIDIAN_VAULT_PATH=${cfg.vaultPath || ''}`,
    '',
  ];

  // API keys per agent
  if (cfg.agents && cfg.agents.length > 0) {
    lines.push('# Brain API keys — one per AI agent');
    for (const agent of cfg.agents) {
      const envName = `KB_API_KEY_${agent.toUpperCase()}`;
      const key = cfg.apiKeys?.[agent] || genHex();
      lines.push(`${envName}=${key}`);
    }
    lines.push('');
  }

  // Auth secret
  lines.push('# Better Auth secret (for OAuth / remote Brain API)');
  lines.push(`BETTER_AUTH_SECRET=${cfg.authSecret || genBase64()}`);
  lines.push('');

  if (cfg.brainApi) {
    lines.push('# Brain API public URL');
    lines.push(`BETTER_AUTH_URL=https://${cfg.brainDomain}`);
    lines.push('');
  }

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Service installation helpers
// ---------------------------------------------------------------------------

function installSystemd() {
  const unit = `[Unit]
Description=Knowledge Base Server
After=network.target

[Service]
Type=simple
User=${process.env.USER || 'root'}
WorkingDirectory=${PROJECT_ROOT}
ExecStart=${process.execPath} ${join(PROJECT_ROOT, 'bin', 'kb.js')} start
Restart=on-failure
RestartSec=5
Environment=NODE_ENV=production

[Install]
WantedBy=multi-user.target
`;
  const unitPath = '/etc/systemd/system/knowledge-base.service';
  try {
    writeFileSync(unitPath, unit);
    execFileSync('systemctl', ['daemon-reload'], { stdio: 'ignore' });
    execFileSync('systemctl', ['enable', 'knowledge-base'], { stdio: 'ignore' });
    return { ok: true, path: unitPath };
  } catch (err) {
    return { ok: false, error: err.message, content: unit };
  }
}

function installLaunchd() {
  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.knowledgebase.server</string>
  <key>ProgramArguments</key>
  <array>
    <string>${process.execPath}</string>
    <string>${join(PROJECT_ROOT, 'bin', 'kb.js')}</string>
    <string>start</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${PROJECT_ROOT}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
</dict>
</plist>
`;
  const plistPath = join(HOME, 'Library', 'LaunchAgents', 'com.knowledgebase.server.plist');
  try {
    mkdirSync(join(HOME, 'Library', 'LaunchAgents'), { recursive: true });
    writeFileSync(plistPath, plist);
    return { ok: true, path: plistPath };
  } catch (err) {
    return { ok: false, error: err.message, content: plist };
  }
}

function generateDockerCompose(cfg) {
  const content = `version: "3.8"
services:
  knowledge-base:
    build: .
    ports:
      - "${cfg.port}:${cfg.port}"
    volumes:
      - kb-data:/root/.knowledge-base
${cfg.vaultPath ? `      - ${cfg.vaultPath}:/vault` : ''}
    env_file:
      - .env
    restart: unless-stopped

volumes:
  kb-data:
`;
  const composePath = join(PROJECT_ROOT, 'docker-compose.yml');
  writeFileSync(composePath, content);
  return composePath;
}

const MCP_REGISTRARS = {
  claude: () => registerAgents(['claude'], HOME)[0].path,
  codex: () => registerAgents(['codex'], HOME)[0].path,
  gemini: () => registerAgents(['gemini'], HOME)[0].path,
};

// ---------------------------------------------------------------------------
// Parse --auto CLI flags
// ---------------------------------------------------------------------------

function parseAutoArgs(args) {
  const cfg = {};
  for (const arg of args) {
    const m = arg.match(/^--(\w[\w-]*)=(.*)$/);
    if (m) {
      const [, key, val] = m;
      if (key === 'port') cfg.port = parseInt(val, 10);
      else if (key === 'password') cfg.password = val;
      else if (key === 'vault') cfg.vaultPath = val === 'none' ? '' : resolve(val.replace(/^~/, HOME));
      else if (key === 'agents') cfg.agents = val.split(',').map(s => s.trim().toLowerCase());
      else if (key === 'deploy') cfg.deploy = val;
      else if (key === 'brain') cfg.brainApi = val === 'true' || val === 'yes';
      else if (key === 'domain') cfg.brainDomain = val;
    }
  }
  return cfg;
}

function loadConfigFile() {
  const configPath = join(PROJECT_ROOT, 'setup-config.json');
  if (!existsSync(configPath)) return null;
  try {
    return JSON.parse(readFileSync(configPath, 'utf-8'));
  } catch { return null; }
}

// ---------------------------------------------------------------------------
// Interactive wizard
// ---------------------------------------------------------------------------

async function runInteractive(env) {
  const rl = createRl();
  const cfg = {};
  const prior = loadExistingEnv();

  // 1. Welcome
  outln();
  outln('========================================');
  outln('  Knowledge Base Server Setup');
  outln('========================================');
  outln();

  // 2. Environment
  outln('  Detected environment:');
  outln(`    OS:   ${env.os}`);
  outln(`    Node: ${env.nodeVersion}`);
  outln(`    AI tools found:`);
  for (const [, info] of Object.entries(env.tools)) {
    outln(`      ${info.available ? '[x]' : '[ ]'} ${info.label}`);
  }
  outln();

  // 3. Dashboard password
  const randomPw = prior.KB_PASSWORD || genHex(8);
  outln('  Dashboard password protects the web UI.');
  outln(prior.KB_PASSWORD
    ? '  Press Enter to keep the existing password, or type a new one.'
    : '  Press Enter to generate a random one, or type your own.');
  cfg.password = await ask(rl, 'Dashboard password', randomPw);

  // 4. Server port
  outln();
  outln('  The dashboard and API will listen on this port.');
  const portStr = await ask(rl, 'Server port', prior.KB_PORT || '3838');
  cfg.port = parseInt(portStr, 10) || 3838;

  // 5. Vault (any markdown dir; Obsidian is an optional viewer)
  outln();
  outln('  The vault is a markdown folder the KB indexes for search.');
  const detected = prior.OBSIDIAN_VAULT_PATH || detectVaultPath();
  const vaultDefault = detected || join(HOME, 'kb-vault');
  if (detected) {
    outln(`  Using vault: ${detected}`);
  }
  outln('  Enter a path (created if missing), or "none" to skip.');
  const vaultAnswer = await ask(rl, 'Vault path', vaultDefault);
  cfg.vaultPath = vaultAnswer === 'none' ? '' : resolve(vaultAnswer.replace(/^~/, HOME));

  // 6. AI agents
  outln();
  outln('  Select which AI agents will connect to the knowledge base.');
  outln('  Each gets a unique API key for authentication.');
  const agentChoices = ['Claude Code', 'OpenAI Codex', 'Google Gemini', 'Ollama'];
  const agentKeys = ['claude', 'codex', 'gemini', 'ollama'];
  const selected = await askMulti(rl, 'Select agents (comma-separated numbers, or A for all)', agentChoices);
  cfg.agents = selected.map(i => agentKeys[i]);
  cfg.apiKeys = {};
  for (const agent of cfg.agents) {
    cfg.apiKeys[agent] = prior[`KB_API_KEY_${agent.toUpperCase()}`] || genHex();
  }

  // 7. Deployment mode
  const deployChoices = [];
  const deployKeys = [];
  if (platform() === 'linux') { deployChoices.push('systemd (auto-start on boot)'); deployKeys.push('systemd'); }
  if (platform() === 'darwin') { deployChoices.push('launchd (auto-start on boot)'); deployKeys.push('launchd'); }
  deployChoices.push('Docker (docker-compose)');
  deployKeys.push('docker');
  deployChoices.push('PM2 (process manager)');
  deployKeys.push('pm2');
  deployChoices.push('Manual (run kb start yourself)');
  deployKeys.push('manual');

  outln();
  outln('  How should the server run?');
  const deployIdx = await askChoice(rl, 'Deployment mode', deployChoices, 0);
  cfg.deploy = deployKeys[deployIdx];

  // 8. Brain API
  outln();
  outln('  The Brain API allows remote HTTPS access from AI agents.');
  outln('  Requires a domain name and reverse proxy (e.g., Caddy, nginx).');
  const brainAnswer = await ask(rl, 'Enable Brain API? (y/N)', 'n');
  cfg.brainApi = brainAnswer.toLowerCase().startsWith('y');
  if (cfg.brainApi) {
    cfg.brainDomain = await ask(rl, 'Domain for Brain API', 'brain.yourdomain.com');
  }

  cfg.authSecret = prior.BETTER_AUTH_SECRET || genBase64();

  rl.close();
  return cfg;
}

// ---------------------------------------------------------------------------
// Apply configuration
// ---------------------------------------------------------------------------

function applyConfig(cfg) {
  const results = { steps: [] };

  // 0. Ensure vault exists (any markdown dir works; Obsidian is an optional viewer)
  if (cfg.vaultPath && !existsSync(cfg.vaultPath)) {
    try {
      mkdirSync(cfg.vaultPath, { recursive: true });
      try {
        execFileSync('bash', [join(PROJECT_ROOT, 'bin', 'init-vault.sh')], {
          env: { ...process.env, OBSIDIAN_VAULT_PATH: cfg.vaultPath }, stdio: 'ignore',
        });
        results.steps.push({ action: 'Created vault with folder taxonomy', path: cfg.vaultPath });
      } catch (err) {
        results.steps.push({ action: 'Created vault (taxonomy script failed; folders optional)', path: cfg.vaultPath, error: err.message });
      }
    } catch (err) {
      results.steps.push({ action: 'Failed to create vault directory', path: cfg.vaultPath, error: err.message });
    }
  }

  // 1. Write .env
  const envContent = buildEnvContent(cfg);
  const envPath = join(PROJECT_ROOT, '.env');
  const envExisted = existsSync(envPath);
  writeFileSync(envPath, envContent);
  results.steps.push({
    action: envExisted ? 'Updated .env' : 'Created .env',
    path: envPath,
  });

  // 2. Register MCP for each agent that has a registrar
  for (const agent of (cfg.agents || [])) {
    if (MCP_REGISTRARS[agent]) {
      try {
        const path = MCP_REGISTRARS[agent]();
        results.steps.push({ action: `Registered MCP for ${agent}`, path });
      } catch (err) {
        results.steps.push({ action: `Failed to register MCP for ${agent}`, error: err.message });
      }
    }
  }

  // 3. Install service
  if (cfg.deploy === 'systemd') {
    const r = installSystemd();
    if (r.ok) {
      results.steps.push({ action: 'Installed systemd service', path: r.path });
    } else {
      results.steps.push({
        action: 'Could not install systemd service (may need sudo)',
        error: r.error,
        hint: 'Save the unit file manually and run: sudo systemctl daemon-reload && sudo systemctl enable knowledge-base',
      });
    }
  } else if (cfg.deploy === 'launchd') {
    const r = installLaunchd();
    if (r.ok) {
      results.steps.push({ action: 'Installed launchd plist', path: r.path });
    } else {
      results.steps.push({ action: 'Could not install launchd plist', error: r.error });
    }
  } else if (cfg.deploy === 'docker') {
    const path = generateDockerCompose(cfg);
    results.steps.push({ action: 'Generated docker-compose.yml', path });
  } else if (cfg.deploy === 'pm2') {
    results.steps.push({
      action: 'PM2 selected',
      hint: 'Run: pm2 start bin/kb.js --name knowledge-base -- start',
    });
  }

  // 4. Claude Code hooks: session briefing + per-prompt KB hints
  if ((cfg.agents || []).includes('claude')) {
    try {
      const r = installClaudeHooks({ home: HOME, nodeBin: process.execPath, kbJsPath: join(PROJECT_ROOT, 'bin', 'kb.js') });
      results.steps.push({ action: 'Installed Claude Code hooks (briefing + hints)', path: r.path });
      if (r.backup) results.steps.push({ action: 'Backed up prior settings.json', path: r.backup });
    } catch (err) {
      results.steps.push({ action: 'Failed to install Claude Code hooks', error: err.message });
    }
  }

  // 5. Scheduled jobs: nightly harvest, reindex, weekly synthesis
  let claudePath = null;
  try { claudePath = execFileSync('which', ['claude']).toString().trim(); } catch { /* optional */ }
  const jobs = installJobs({
    home: HOME, nodeBin: process.execPath, kbRoot: PROJECT_ROOT,
    vaultPath: cfg.vaultPath, claudePath, load: cfg.loadJobs !== false,
  });
  results.steps.push(...jobs.steps);
  if (!claudePath) results.steps.push({ action: 'claude CLI not found — nightly harvest needs it; install Claude Code and re-run setup', error: 'CLAUDE_PATH unset' });

  // 6. Bundled skills — never overwrite a skill the user already has (customizations win)
  try {
    for (const name of readdirSync(join(PROJECT_ROOT, 'skills'))) {
      const skillDest = join(HOME, '.claude', 'skills', name);
      try {
        if (existsSync(skillDest)) {
          results.steps.push({ action: `Skill ${name} already present — left untouched`, path: skillDest });
          continue;
        }
        cpSync(join(PROJECT_ROOT, 'skills', name), skillDest, { recursive: true });
        results.steps.push({ action: `Installed ${name} skill`, path: skillDest });
      } catch (err) {
        results.steps.push({ action: `Failed to install ${name} skill`, error: err.message });
      }
    }
  } catch (err) {
    results.steps.push({ action: 'Failed to read bundled skills directory', error: err.message });
  }

  // 7. First ingest if vault provided
  if (cfg.vaultPath && existsSync(cfg.vaultPath)) {
    results.ingestPath = cfg.vaultPath;
  }

  results.cfg = cfg;
  return results;
}

// ---------------------------------------------------------------------------
// Print summary
// ---------------------------------------------------------------------------

function printSummary(results) {
  outln();
  outln('========================================');
  outln('  Setup Complete');
  outln('========================================');
  outln();

  for (const step of results.steps) {
    outln(`  [done] ${step.action}`);
    if (step.path) outln(`         ${step.path}`);
    if (step.hint) outln(`         ${step.hint}`);
    if (step.error) outln(`         Error: ${step.error}`);
  }

  const cfg = results.cfg;
  outln();
  outln('  SENSITIVE — do not share or log the following values:');
  outln('  Configuration summary:');
  outln(`    Port:      ${cfg.port}`);
  outln(`    Password:  ${cfg.password}`);
  outln(`    Vault:     ${cfg.vaultPath || '(none)'}`);
  outln(`    Agents:    ${(cfg.agents || []).join(', ') || '(none)'}`);
  outln(`    Deploy:    ${cfg.deploy || 'manual'}`);
  if (cfg.brainApi) {
    outln(`    Brain API: https://${cfg.brainDomain}`);
  }

  if (cfg.apiKeys && Object.keys(cfg.apiKeys).length > 0) {
    outln();
    outln('  SENSITIVE — do not share or log the following values:');
    outln('  API keys (save these — they are not stored elsewhere):');
    for (const [agent, key] of Object.entries(cfg.apiKeys)) {
      outln(`    ${agent}: ${key}`);
    }
  }

  outln();
  outln('  Next steps:');
  outln('    1. Review .env and adjust if needed');
  if (results.ingestPath) {
    outln(`    2. Run: kb ingest ${results.ingestPath}`);
    outln('    3. Run: kb start');
  } else {
    outln('    2. Run: kb start');
  }
  outln(`    Dashboard: http://localhost:${cfg.port}`);
  outln();
  outln('Open a new Claude Code session — your first KB BRIEFING should appear at startup.');
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

export async function setup(args = []) {
  const isAuto = args.includes('--auto');

  const env = detectEnvironment();

  if (isAuto) {
    // Agent mode: combine config file + CLI flags, no prompts
    const fileConfig = loadConfigFile() || {};
    const cliConfig = parseAutoArgs(args);
    const merged = { ...fileConfig, ...cliConfig };

    // Apply defaults for anything not specified; preserve existing secrets on re-run.
    const prior = loadExistingEnv();
    const cfg = {
      port: merged.port || prior.KB_PORT || 3838,
      password: merged.password || prior.KB_PASSWORD || genHex(8),
      // A non-empty vaultPath (from setup-config.json or --vault) gets the same
      // tilde/relative resolution the flag and interactive paths apply; '' keeps
      // the `--vault=none` skip-vault semantics.
      vaultPath: (typeof merged.vaultPath === 'string' && merged.vaultPath)
        ? resolve(merged.vaultPath.replace(/^~/, HOME))
        : (merged.vaultPath !== undefined ? merged.vaultPath
          : (prior.OBSIDIAN_VAULT_PATH || detectVaultPath() || join(HOME, 'kb-vault'))),
      agents: merged.agents || Object.keys(env.tools).filter(k => env.tools[k].available),
      deploy: merged.deploy || 'manual',
      brainApi: merged.brainApi || false,
      brainDomain: merged.brainDomain || 'brain.yourdomain.com',
      authSecret: merged.authSecret || prior.BETTER_AUTH_SECRET || genBase64(),
      apiKeys: {},
      loadJobs: !args.includes('--no-load-jobs'),
    };

    // Generate API keys for each agent, reusing prior keys so registered agents keep working.
    for (const agent of cfg.agents) {
      cfg.apiKeys[agent] = merged.apiKeys?.[agent] || prior[`KB_API_KEY_${agent.toUpperCase()}`] || genHex();
    }

    outln('Knowledge Base Server — automatic setup');
    outln();

    const results = applyConfig(cfg);
    printSummary(results);
    return;
  }

  // Interactive mode
  const cfg = await runInteractive(env);
  const results = applyConfig(cfg);
  printSummary(results);
}
